# Generated by Django 5.2.6 on 2025-12-07 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=300)),
                ('date_naissance', models.DateField()),
                ('date_creation', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('nom_parent', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_nutrition', models.CharField(max_length=100)),
                ('date_visite', models.DateField()),
                ('date_admission', models.DateField()),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('etat_nutrition', models.CharField(max_length=500)),
                ('motif_sortie', models.CharField(blank=True, max_length=255, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poids', models.FloatField()),
                ('taille', models.FloatField()),
                ('perimetre_brachial', models.FloatField(blank=True, null=True)),
                ('zscore', models.FloatField()),
                ('imc', models.FloatField()),
                ('indicecorporel', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depiste', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], max_length=10)),
                ('code_depistage', models.CharField(blank=True, max_length=50, null=True)),
                ('resultat', models.CharField(blank=True, choices=[('positif', 'Positif'), ('negatif', 'Négatif')], max_length=10, null=True)),
                ('produits', models.JSONField(default=list)),
                ('date_enregistrement', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vaccin', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
