# Generated by Django 5.2.6 on 2025-09-17 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=300)),
                ('date_naissance', models.DateField()),
                ('nom_parent', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unique', models.CharField()),
                ('date_visite', models.DateField()),
                ('date_admission', models.DateField()),
                ('date_sortie', models.DateField()),
                ('etat_nutrition', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poids', models.FloatField()),
                ('taille', models.FloatField()),
                ('perimetre_brachial', models.FloatField()),
                ('imc', models.FloatField()),
                ('indicecorporel', models.CharField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Autreservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('depistage', models.CharField(max_length=100)),
                ('codedepistage', models.TextField()),
                ('resultattest', models.TextField()),
                ('vitamina_dose1', models.TextField()),
                ('vitamina_dose2', models.TextField()),
                ('plumpynut', models.TextField()),
                ('deparasitant', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bcg', models.CharField(max_length=100)),
                ('polio0', models.CharField(max_length=100)),
                ('vpo', models.CharField(max_length=100)),
                ('dtc', models.CharField(max_length=100)),
                ('pcv', models.CharField(max_length=100)),
                ('vpi', models.CharField(max_length=100)),
                ('rota', models.CharField(max_length=100)),
                ('vaa', models.CharField(max_length=100)),
                ('var', models.CharField(max_length=100)),
                ('vat', models.CharField(max_length=100)),
                ('vam', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
