# Generated by Django 5.1.6 on 2025-10-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=300)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('nom_parent', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unique', models.CharField(max_length=100)),
                ('date_visite', models.DateField()),
                ('date_admission', models.DateField()),
                ('date_sortie', models.DateField()),
                ('etat_nutrition', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('poids', models.FloatField()),
                ('taille', models.FloatField()),
                ('perimetre_brachial', models.FloatField()),
                ('zscore', models.FloatField()),
                ('imc', models.FloatField()),
                ('indicecorporel', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vaccin', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('depistage', models.CharField(max_length=100)),
                ('codedepistage', models.TextField()),
                ('resultattest', models.TextField()),
                ('vitamina_dose1', models.TextField()),
                ('vitamina_dose2', models.TextField()),
                ('plumpynut', models.TextField()),
                ('deparasitant', models.TextField()),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.nutrition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('vaccination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.vaccination')),
            ],
        ),
    ]
