# Generated by Django 5.1.6 on 2025-10-25 23:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='code_unique',
            new_name='code_nutrition',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='motif_sortie',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
