# Generated by Django 5.1.6 on 2026-01-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='depiste',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='Non', max_length=10),
        ),
    ]
