# Generated by Django 5.1.6 on 2025-10-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rename_code_unique_nutrition_code_nutrition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
