# Generated by Django 5.1.6 on 2026-02-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_rdv_depiste'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='statut',
            field=models.CharField(default='enfant', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rdv',
            name='depiste',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='non', max_length=10),
        ),
    ]
