# Generated by Django 5.1.6 on 2025-10-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_nutrition_date_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='motif_sortie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
