# Generated by Django 5.1.6 on 2025-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_nutrition_motif_sortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constante',
            name='perimetre_brachial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
