# Generated by Django 5.1.6 on 2025-10-26 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_constante_perimetre_brachial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='codedepistage',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='deparasitant',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='depistage',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='plumpynut',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='resultattest',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='vaccination',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='vitamina_dose1',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='vitamina_dose2',
        ),
        migrations.AddField(
            model_name='rdv',
            name='code_depistage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rdv',
            name='date_enregistrement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rdv',
            name='depiste',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rdv',
            name='produits',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='rdv',
            name='resultat',
            field=models.CharField(choices=[('positif', 'Positif'), ('negatif', 'Négatif')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
