# Generated by Django 5.1.6 on 2025-10-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_rdv_codedepistage_remove_rdv_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='resultat',
            field=models.CharField(blank=True, choices=[('positif', 'Positif'), ('negatif', 'Négatif')], max_length=10, null=True),
        ),
    ]
