# Generated by Django 5.1.6 on 2025-11-12 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_rdv_resultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
